// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PensionManagementSystem.Data;

#nullable disable

namespace JWTAuthentication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220810105057_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PensionManagementSystem.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("AccountNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = 9876543210L,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = 7894561230L,
                            Type = 0
                        });
                });

            modelBuilder.Entity("PensionManagementSystem.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thread")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("PensionManagementSystem.Models.PensionerDetail", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<long>("AadhaarNumber")
                        .HasColumnType("bigint");

                    b.Property<double>("Allowances")
                        .HasColumnType("float");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SalaryEarned")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("BankId");

                    b.ToTable("PensionerDetails");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AadhaarNumber = 1234567898012L,
                            Allowances = 5000.0,
                            BankId = 1,
                            DateOfBirth = new DateTime(2022, 8, 10, 16, 20, 57, 457, DateTimeKind.Local).AddTicks(7615),
                            Name = "User one",
                            PAN = "PAN9876543",
                            SalaryEarned = 30000.0,
                            Type = 0
                        },
                        new
                        {
                            UserId = 2,
                            AadhaarNumber = 1234567898013L,
                            Allowances = 4500.0,
                            BankId = 2,
                            DateOfBirth = new DateTime(2022, 8, 11, 16, 20, 57, 457, DateTimeKind.Local).AddTicks(7633),
                            Name = "User two",
                            PAN = "PAN7894562",
                            SalaryEarned = 32000.0,
                            Type = 0
                        });
                });

            modelBuilder.Entity("PensionManagementSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "VXNlcjE=",
                            Username = "User1"
                        },
                        new
                        {
                            Id = 2,
                            Password = "VXNlcjI=",
                            Username = "User2"
                        });
                });

            modelBuilder.Entity("PensionManagementSystem.Models.PensionerDetail", b =>
                {
                    b.HasOne("PensionManagementSystem.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PensionManagementSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
